# Generated by Django 6.1.1 on 2026-09-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishmentprofile',
            name='is_active_safe_haven',
        ),
        migrations.RemoveField(
            model_name='establishmentprofile',
            name='safe_phrase',
        ),
        migrations.RemoveField(
            model_name='establishmentprofile',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='establishmentprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='SafeHaven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('safe_phrase', models.CharField(default='I need a lighthouse', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('people_helped', models.PositiveIntegerField(default=0)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_havens', to='establishment_profile.establishmentprofile')),
            ],
        ),
    ]
