# Generated by Django 6.1.1 on 2026-09-15 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment_profile', '0002_remove_establishmentprofile_is_active_safe_haven_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='establishment_profile.establishmentprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
